apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/gke-free-lab/demo-app-repo/backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MONGO_HOST
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB
              value: "moviesdb"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-app-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-app-password
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
