apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
stringData:
  mongo-root-username: mongoadmin
  mongo-root-password: mongoadmin123
  mongo-app-username: moviesapp
  mongo-app-password: moviesapp123
