apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-configmap
  namespace: default
data:
  init-mongo.sh: |
    #!/bin/sh
    set -e

    cat <<EOF >/tmp/init-mongo.js
    db = db.getSiblingDB("moviesdb");
    db.createUser({
      user: "${MONGO_APP_USERNAME}",
      pwd: "${MONGO_APP_PASSWORD}",
      roles: [
        {
          role: "readWrite",
          db: "moviesdb"
        }
      ]
    });
    EOF

    mongosh --authenticationDatabase admin \
      -u "${MONGO_INITDB_ROOT_USERNAME}" \
      -p "${MONGO_INITDB_ROOT_PASSWORD}" \
      /tmp/init-mongo.js
